#pragma once

#include "NativeGameplayTags.h"

namespace CCLTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Guard);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Parry);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Busy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stagger);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Guard);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parry);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_RecoveryDelay);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Life);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Magnitude);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Outcome_Rejected);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Outcome_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Outcome_Evaded);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Outcome_Parried);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Outcome_Guarded);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Outcome_GuardBroken);
}
