#include "CCLAgentTags.h"

namespace CCLAgentTags
{
UE_DEFINE_GAMEPLAY_TAG(Feature_Traits, "Agent.Feature.Traits");
UE_DEFINE_GAMEPLAY_TAG(Feature_Life, "Agent.Feature.Life");
UE_DEFINE_GAMEPLAY_TAG(Feature_Resources, "Agent.Feature.Resources");
UE_DEFINE_GAMEPLAY_TAG(Feature_Experience, "Agent.Feature.Experience");
UE_DEFINE_GAMEPLAY_TAG(Feature_Needs, "Agent.Feature.Needs");
UE_DEFINE_GAMEPLAY_TAG(RiskTolerance, "Agent.Trait.RiskTolerance");
UE_DEFINE_GAMEPLAY_TAG(Aggressiveness, "Agent.Trait.Aggressiveness");
UE_DEFINE_GAMEPLAY_TAG(Curiosity, "Agent.Trait.Curiosity");
UE_DEFINE_GAMEPLAY_TAG(Sociability, "Agent.Trait.Sociability");
UE_DEFINE_GAMEPLAY_TAG(SelfControl, "Agent.Trait.SelfControl");
UE_DEFINE_GAMEPLAY_TAG(Empathy, "Agent.Trait.Empathy");
UE_DEFINE_GAMEPLAY_TAG(MaterialGain, "Agent.Value.MaterialGain");
UE_DEFINE_GAMEPLAY_TAG(Duty, "Agent.Value.Duty");
UE_DEFINE_GAMEPLAY_TAG(OthersWelfare, "Agent.Value.OthersWelfare");
UE_DEFINE_GAMEPLAY_TAG(Hunger, "Agent.Need.Hunger");
UE_DEFINE_GAMEPLAY_TAG(Fatigue, "Agent.Need.Fatigue");
UE_DEFINE_GAMEPLAY_TAG(Safety, "Agent.Need.Safety");
UE_DEFINE_GAMEPLAY_TAG(Social, "Agent.Need.Social");
UE_DEFINE_GAMEPLAY_TAG(Work, "Agent.Activity.Work");
UE_DEFINE_GAMEPLAY_TAG(Trade, "Agent.Activity.Trade");
UE_DEFINE_GAMEPLAY_TAG(Eat, "Agent.Activity.Eat");
UE_DEFINE_GAMEPLAY_TAG(Rest, "Agent.Activity.Rest");
UE_DEFINE_GAMEPLAY_TAG(Help, "Agent.Activity.Help");
UE_DEFINE_GAMEPLAY_TAG(Repay, "Agent.Activity.Repay");
UE_DEFINE_GAMEPLAY_TAG(Improve, "Agent.Activity.Improve");
UE_DEFINE_GAMEPLAY_TAG(Discover, "Agent.Activity.Discover");
UE_DEFINE_GAMEPLAY_TAG(Goal_Living, "Agent.Goal.Living");
UE_DEFINE_GAMEPLAY_TAG(Goal_Debt, "Agent.Goal.Debt");
UE_DEFINE_GAMEPLAY_TAG(Goal_Support, "Agent.Goal.Support");
UE_DEFINE_GAMEPLAY_TAG(Goal_Business, "Agent.Goal.Business");
UE_DEFINE_GAMEPLAY_TAG(Goal_Mastery, "Agent.Goal.Mastery");
UE_DEFINE_GAMEPLAY_TAG(Active, "Agent.Status.Active");
UE_DEFINE_GAMEPLAY_TAG(Completed, "Agent.Status.Completed");
UE_DEFINE_GAMEPLAY_TAG(Failed, "Agent.Status.Failed");
UE_DEFINE_GAMEPLAY_TAG(Agent, "Agent.Target.Agent");
UE_DEFINE_GAMEPLAY_TAG(Place, "Agent.Target.Place");
UE_DEFINE_GAMEPLAY_TAG(Unknown, "Agent.Target.Unknown");
UE_DEFINE_GAMEPLAY_TAG(Merchant, "Agent.Occupation.Merchant");
UE_DEFINE_GAMEPLAY_TAG(Food, "Agent.Resource.Food");
UE_DEFINE_GAMEPLAY_TAG(Material, "Agent.Resource.Material");
UE_DEFINE_GAMEPLAY_TAG(Family, "Agent.Link.Family");
UE_DEFINE_GAMEPLAY_TAG(Colleague, "Agent.Link.Colleague");
UE_DEFINE_GAMEPLAY_TAG(Fear, "Agent.Emotion.Fear");
UE_DEFINE_GAMEPLAY_TAG(Anger, "Agent.Emotion.Anger");
UE_DEFINE_GAMEPLAY_TAG(Success, "Agent.Event.Success");
UE_DEFINE_GAMEPLAY_TAG(Failure, "Agent.Event.Failure");
UE_DEFINE_GAMEPLAY_TAG(Aid, "Agent.Event.Aid");
}
